version: '3.8'

services:
  zwift-discord-bot:
    build: .
    container_name: zwift-discord-bot
    environment:
      - DISCORD_BOT_TOKEN
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
