version: '3.8'

services:
  zwift-discord-bot:
    build: .
    container_name: zwift-discord-bot
    environment:
      - DISCORD_BOT_TOKEN
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
