version: '3.8'

services:
  zwift-route-bot:
    build: .
    container_name: zwift-route-bot
    environment:
      - DISCORD_BOT_TOKEN
    restart: unless-stopped
    volumes:
      # Mount the route_images directory
      - /home/micah-reeves/Desktop/zwift-route-bot/route_images:/app/route_images
      # Add dedicated volume for cache persistence
      - /home/micah-reeves/Desktop/zwift-route-bot/data:/app/data
    # Update entrypoint to initialize and verify directories
    entrypoint: >
      sh -c "
        echo 'Listing mounted directories:' &&
        echo 'Profiles directory:' &&
        ls -la /app/route_images/profiles &&
        echo 'Maps directory:' &&
        ls -la /app/route_images/maps &&
        echo 'Setting up data directory for cache:' &&
        mkdir -p /app/data &&
        echo 'Data directory contents:' &&
        ls -la /app/data &&
        python zwiftroutebot.py
      "